export const mockMedia = [
  // 1. INCEPTION (Sci-Fi, Action, Thriller)
  {
    id: 1,
    title: "Inception",
    type: "movie",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the sub-conscious of his targets, is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "/8Zg0n57521j4Ggu3fN622aZ362w.jpg",
    vote_average: 8.4,
    release_date: "2010-07-16",
    runtime: 148,
    genres: ["Sci-Fi", "Action", "Thriller"],
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    director: "Christopher Nolan",
    production: "Warner Bros. Pictures",
    trailer_url: "https://www.youtube.com/embed/YoHD9XEInc0"
  },
  // 2. THE DARK KNIGHT (Action, Drama, Thriller)
  {
    id: 2,
    title: "The Dark Knight",
    type: "movie",
    overview: "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/nMKdUUueJZ57qtjTRLBUSBmge6c.jpg",
    vote_average: 8.5,
    release_date: "2008-07-18",
    runtime: 152,
    genres: ["Action", "Drama", "Thriller"],
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Maggie Gyllenhaal"],
    director: "Christopher Nolan",
    production: "Warner Bros. Pictures",
    trailer_url: "https://www.youtube.com/embed/EXeTwQWrcwY"
  },
  // 3. INTERSTELLAR (Sci-Fi, Drama)
  {
    id: 3,
    title: "Interstellar",
    type: "movie",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/rAiw1ptqydR4u6sgzcj5q66Jt6c.jpg",
    vote_average: 8.4,
    release_date: "2014-11-05",
    runtime: 169,
    genres: ["Sci-Fi", "Drama"],
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    director: "Christopher Nolan",
    production: "Paramount Pictures",
    trailer_url: "https://www.youtube.com/embed/zSWdZVtXT7E"
  },
  // 4. DUNE: PART TWO (Sci-Fi, Action, Drama)
  {
    id: 4,
    title: "Dune: Part Two",
    type: "movie",
    overview: "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    poster_path: "/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdrop_path: "/xOMo8BRK7eVWQ7v44aZJuL66u2m.jpg",
    vote_average: 8.3,
    release_date: "2024-02-27",
    runtime: 166,
    genres: ["Sci-Fi", "Action", "Drama"],
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Austin Butler"],
    director: "Denis Villeneuve",
    production: "Legendary Pictures",
    trailer_url: "https://www.youtube.com/embed/Way9Dexny3w"
  },
  // 5. SPIDER-MAN: INTO THE SPIDER-VERSE (Action, Comedy, Sci-Fi)
  {
    id: 5,
    title: "Spider-Man: Into the Spider-Verse",
    type: "movie",
    overview: "Struggling to find his place in the world while juggling school and friends, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops superpowers. When the infamous Kingpin constructs a portal to other dimensions, different Spider-heroes from alternate universes are pulled into Miles' world.",
    poster_path: "/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    backdrop_path: "/7d5a576208Cc5U1tM636uF2uL8O.jpg",
    vote_average: 8.4,
    release_date: "2018-12-06",
    runtime: 117,
    genres: ["Action", "Comedy", "Sci-Fi"],
    cast: ["Shameik Moore", "Jake Johnson", "Hailee Steinfeld", "Mahershala Ali"],
    director: "Bob Persichetti",
    production: "Sony Pictures",
    trailer_url: "https://www.youtube.com/embed/g4HbzQFqcJD"
  },
  // 6. EVERYTHING EVERYWHERE ALL AT ONCE (Sci-Fi, Action, Comedy)
  {
    id: 6,
    title: "Everything Everywhere All at Once",
    type: "movie",
    overview: "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.",
    poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
    backdrop_path: "/5Pv262zSj6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.1,
    release_date: "2022-03-24",
    runtime: 139,
    genres: ["Sci-Fi", "Action", "Comedy"],
    cast: ["Michelle Yeoh", "Ke Huy Quan", "Stephanie Hsu", "Jamie Lee Curtis"],
    director: "Daniel Kwan, Daniel Scheinert",
    production: "A24",
    trailer_url: "https://www.youtube.com/embed/wxN1T1UxQ2A"
  },
  // 7. THE MATRIX (Sci-Fi, Action)
  {
    id: 7,
    title: "The Matrix",
    type: "movie",
    overview: "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_path: "/7R624icgAX5VOwHbc1g36UggOAc.jpg",
    vote_average: 8.2,
    release_date: "1999-03-30",
    runtime: 136,
    genres: ["Sci-Fi", "Action"],
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
    director: "Lana Wachowski, Lilly Wachowski",
    production: "Warner Bros. Pictures",
    trailer_url: "https://www.youtube.com/embed/vKQi3bBA1y8"
  },
  // 8. PARASITE (Drama, Thriller)
  {
    id: 8,
    title: "Parasite",
    type: "movie",
    overview: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "/hiKazoRsw2m9qg6511g2w15asOB.jpg",
    vote_average: 8.5,
    release_date: "2019-05-30",
    runtime: 132,
    genres: ["Drama", "Thriller"],
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    director: "Bong Joon Ho",
    production: "Barunson E&A",
    trailer_url: "https://www.youtube.com/embed/5xH0HfJHsaY"
  },
  // 9. PULP FICTION (Drama, Thriller)
  {
    id: 9,
    title: "Pulp Fiction",
    type: "movie",
    overview: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll, and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
    poster_path: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop_path: "/sua754O3z6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.5,
    release_date: "1994-09-10",
    runtime: 154,
    genres: ["Drama", "Thriller"],
    cast: ["John Travolta", "Samuel L. Jackson", "Uma Thurman", "Bruce Willis"],
    director: "Quentin Tarantino",
    production: "Miramax",
    trailer_url: "https://www.youtube.com/embed/s7EgWv7962Y"
  },
  // 10. AVENGERS: ENDGAME (Action, Sci-Fi)
  {
    id: 10,
    title: "Avengers: Endgame",
    type: "movie",
    overview: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_path: "/7Ry7z6j2E7OAJB1gj9xt7a92w1.jpg",
    vote_average: 8.3,
    release_date: "2019-04-24",
    runtime: 181,
    genres: ["Action", "Sci-Fi"],
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    director: "Anthony Russo, Joe Russo",
    production: "Marvel Studios",
    trailer_url: "https://www.youtube.com/embed/TcMBFSGVi1c"
  },
  // 11. KNIVES OUT (Comedy, Thriller)
  {
    id: 11,
    title: "Knives Out",
    type: "movie",
    overview: "When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate. From Harlan's dysfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth.",
    poster_path: "/pThyQovXQrw2m0s9x82twj48Jq4.jpg",
    backdrop_path: "/qZd7t9gBj55J82eZeffuBsua7.jpg",
    vote_average: 7.9,
    release_date: "2019-11-27",
    runtime: 130,
    genres: ["Comedy", "Thriller"],
    cast: ["Daniel Craig", "Chris Evans", "Ana de Armas", "Jamie Lee Curtis"],
    director: "Rian Johnson",
    production: "Lionsgate",
    trailer_url: "https://www.youtube.com/embed/qGqiHJTsRkQ"
  },
  // 12. SUPERBAD (Comedy)
  {
    id: 12,
    title: "Superbad",
    type: "movie",
    overview: "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a booze-soaked party goes awry.",
    poster_path: "/ek8e8txUyUwd2BNqj6lFEerJfbq.jpg",
    backdrop_path: "/1t8k9Xn9B2ZtG3yR7Kk314v9ts5.jpg",
    vote_average: 7.2,
    release_date: "2007-08-17",
    runtime: 113,
    genres: ["Comedy"],
    cast: ["Jonah Hill", "Michael Cera", "Christopher Mintz-Plasse", "Seth Rogen"],
    director: "Greg Mottola",
    production: "Columbia Pictures",
    trailer_url: "https://www.youtube.com/embed/4eaZsuVgp3s"
  },
  // 13. THE HANGOVER (Comedy)
  {
    id: 13,
    title: "The Hangover",
    type: "movie",
    overview: "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.",
    poster_path: "/uluhlXubGu1VxU63X9VHCLWDAYP.jpg",
    backdrop_path: "/56v2a6t0YwHbc1g36UggOAcHd65.jpg",
    vote_average: 7.3,
    release_date: "2009-06-02",
    runtime: 100,
    genres: ["Comedy"],
    cast: ["Bradley Cooper", "Ed Helms", "Zach Galifianakis", "Justin Bartha"],
    director: "Todd Phillips",
    production: "Warner Bros. Pictures",
    trailer_url: "https://www.youtube.com/embed/tcdUjFnMdB8"
  },
  // 14. BARBIE (Comedy, Drama)
  {
    id: 14,
    title: "Barbie",
    type: "movie",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    poster_path: "/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
    backdrop_path: "/ctMserH8g2kgvQCzA5MK06w5BOu.jpg",
    vote_average: 7.2,
    release_date: "2023-07-19",
    runtime: 114,
    genres: ["Comedy", "Drama"],
    cast: ["Margot Robbie", "Ryan Gosling", "America Ferrera", "Kate McKinnon"],
    director: "Greta Gerwig",
    production: "LuckyChap Entertainment",
    trailer_url: "https://www.youtube.com/embed/pBk4NYhWNMM"
  },
  // 15. WHIPLASH (Drama)
  {
    id: 15,
    title: "Whiplash",
    type: "movie",
    overview: "Under the direction of a ruthless instructor, a talented young drummer begins to pursue perfection at any cost, even his humanity.",
    poster_path: "/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop_path: "/oNXjKVFu27t9gBj55J82eZeffuB.jpg",
    vote_average: 8.4,
    release_date: "2014-10-10",
    runtime: 107,
    genres: ["Drama"],
    cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser", "Melissa Benoist"],
    director: "Damien Chazelle",
    production: "Bold Films",
    trailer_url: "https://www.youtube.com/embed/7d_jQyG83_w"
  },
  // 16. THE GODFATHER (Drama)
  {
    id: 16,
    title: "The Godfather",
    type: "movie",
    overview: "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone, barely survives an attempt on his life, his youngest son, Michael, steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdrop_path: "/tmU7CekSVNzt5ZUsS3ZYiRjZNuF.jpg",
    vote_average: 8.7,
    release_date: "1972-03-14",
    runtime: 175,
    genres: ["Drama"],
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
    director: "Francis Ford Coppola",
    production: "Paramount Pictures",
    trailer_url: "https://www.youtube.com/embed/UaVTIH8mujA"
  },
  // 17. THE SHAWSHANK REDEMPTION (Drama)
  {
    id: 17,
    title: "The Shawshank Redemption",
    type: "movie",
    overview: "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long years in prison, Dufresne befriends a band of fellow inmates, most notably a wise long-term prisoner named Red.",
    poster_path: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop_path: "/kXfqK2UB68R762eVNE86jX08tV.jpg",
    vote_average: 8.7,
    release_date: "1994-09-23",
    runtime: 142,
    genres: ["Drama"],
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    director: "Frank Darabont",
    production: "Castle Rock Entertainment",
    trailer_url: "https://www.youtube.com/embed/PLl99DlL6b4"
  },
  // 18. SE7EN (Thriller, Horror)
  {
    id: 18,
    title: "Se7en",
    type: "movie",
    overview: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
    poster_path: "/191nKfP0ehp3uIvWqgPbFmI4lv9.jpg",
    backdrop_path: "/3NXjKVFu27t9gBj55J82eZeffuB.jpg",
    vote_average: 8.4,
    release_date: "1995-09-22",
    runtime: 127,
    genres: ["Thriller", "Horror"],
    cast: ["Brad Pitt", "Morgan Freeman", "Gwyneth Paltrow", "Kevin Spacey"],
    director: "David Fincher",
    production: "New Line Cinema",
    trailer_url: "https://www.youtube.com/embed/znmZoVkCjDY"
  },
  // 19. SHUTTER ISLAND (Thriller, Drama)
  {
    id: 19,
    title: "Shutter Island",
    type: "movie",
    overview: "World War II soldier turned U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane on Shutter Island.",
    poster_path: "/nrmXQ0zcZUL8jFLrakWc90IR8z9.jpg",
    backdrop_path: "/8Zg0n57521j4Ggu3fN622aZ362w.jpg",
    vote_average: 8.2,
    release_date: "2010-02-14",
    runtime: 138,
    genres: ["Thriller", "Drama"],
    cast: ["Leonardo DiCaprio", "Mark Ruffalo", "Ben Kingsley", "Michelle Williams"],
    director: "Martin Scorsese",
    production: "Paramount Pictures",
    trailer_url: "https://www.youtube.com/embed/5iaYLCip5Qk"
  },
  // 20. THE SILENCE OF THE LAMBS (Thriller, Horror)
  {
    id: 20,
    title: "The Silence of the Lambs",
    type: "movie",
    overview: "Clarice Starling, a young FBI trainee, is assigned to help find a missing woman and save her from a psychopathic serial killer who skins his victims. To do so, Clarice attempts to gain the advice of another incarcerated killer: the brilliant but deadly psychiatrist, Dr. Hannibal Lecter.",
    poster_path: "/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
    backdrop_path: "/hiKazoRsw2m9qg6511g2w15asOB.jpg",
    vote_average: 8.3,
    release_date: "1991-01-30",
    runtime: 118,
    genres: ["Thriller", "Horror"],
    cast: ["Jodie Foster", "Anthony Hopkins", "Scott Glenn", "Ted Levine"],
    director: "Jonathan Demme",
    production: "Orion Pictures",
    trailer_url: "https://www.youtube.com/embed/W6Mm8SbeTXo"
  },
  // 21. GET OUT (Horror, Thriller)
  {
    id: 21,
    title: "Get Out",
    type: "movie",
    overview: "Chris and his girlfriend Rose go upstate to visit her parents for the weekend. At first, Chris reads the family's overly accommodating behavior as nervous attempts to deal with their daughter's interracial relationship, but as the weekend progresses, a series of increasingly disturbing discoveries lead him to a truth that he could never have imagined.",
    poster_path: "/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg",
    backdrop_path: "/5Pv262zSj6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 7.6,
    release_date: "2017-02-24",
    runtime: 104,
    genres: ["Horror", "Thriller"],
    cast: ["Daniel Kaluuya", "Allison Williams", "Catherine Keener", "Bradley Whitford"],
    director: "Jordan Peele",
    production: "Blumhouse Productions",
    trailer_url: "https://www.youtube.com/embed/sRfnevzM9kQ"
  },
  // 22. A NIGHTMARE ON ELM STREET (Horror)
  {
    id: 22,
    title: "A Nightmare on Elm Street",
    type: "movie",
    overview: "Teenagers in a small town are drops of blood for the razor-clawed hands of Freddy Krueger, a disfigured serial killer who preys on them in their dreams.",
    poster_path: "/wGTpGGRMZmyFCcrY2YoxVTIBlli.jpg",
    backdrop_path: "/sua754O3z6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 7.5,
    release_date: "1984-11-09",
    runtime: 91,
    genres: ["Horror"],
    cast: ["Heather Langenkamp", "Robert Englund", "Johnny Depp", "John Saxon"],
    director: "Wes Craven",
    production: "New Line Cinema",
    trailer_url: "https://www.youtube.com/embed/dCVh4lBfW-c"
  },
  // 23. HEREDITARY (Horror, Drama)
  {
    id: 23,
    title: "Hereditary",
    type: "movie",
    overview: "When Ellen, the matriarch of the Graham family, passes away, her daughter's family begins to unravel cryptic and increasingly terrifying secrets about their ancestry. The more they discover, the more they find themselves trying to outrun the sinister fate they seem to have inherited.",
    poster_path: "/p9fmuz2Oj3HtEJEqbIwkFGUhVXD.jpg",
    backdrop_path: "/7Ry7z6j2E7OAJB1gj9xt7a92w1.jpg",
    vote_average: 7.3,
    release_date: "2018-06-08",
    runtime: 127,
    genres: ["Horror", "Drama"],
    cast: ["Toni Collette", "Alex Wolff", "Milly Shapiro", "Gabriel Byrne"],
    director: "Ari Aster",
    production: "A24",
    trailer_url: "https://www.youtube.com/embed/V6wWKNij_1M"
  },
  // 24. THE CONJURING (Horror, Thriller)
  {
    id: 24,
    title: "The Conjuring",
    type: "movie",
    overview: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    poster_path: "/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    backdrop_path: "/nMKdUUueJZ57qtjTRLBUSBmge6c.jpg",
    vote_average: 7.5,
    release_date: "2013-07-19",
    runtime: 112,
    genres: ["Horror", "Thriller"],
    cast: ["Vera Farmiga", "Patrick Wilson", "Lili Taylor", "Ron Livingston"],
    director: "James Wan",
    production: "New Line Cinema",
    trailer_url: "https://www.youtube.com/embed/k10ETZ41q5o"
  },
  // 25. TITANIC (Romance, Drama)
  {
    id: 25,
    title: "Titanic",
    type: "movie",
    overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure to its death on its first and last voyage.",
    poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
    backdrop_path: "/6zL2t9gBj55J82eZeffuBsua7Ry.jpg",
    vote_average: 7.9,
    release_date: "1997-11-18",
    runtime: 194,
    genres: ["Romance", "Drama"],
    cast: ["Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "Kathy Bates"],
    director: "James Cameron",
    production: "20th Century Fox",
    trailer_url: "https://www.youtube.com/embed/CHekzSiZ47I"
  },
  // 26. LA LA LAND (Romance, Drama, Comedy)
  {
    id: 26,
    title: "La La Land",
    type: "movie",
    overview: "Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.",
    poster_path: "/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    backdrop_path: "/ts54t8k9Xn9B2ZtG3yR7Kk314v9.jpg",
    vote_average: 7.9,
    release_date: "2016-11-29",
    runtime: 128,
    genres: ["Romance", "Drama", "Comedy"],
    cast: ["Ryan Gosling", "Emma Stone", "John Legend", "Rosemarie DeWitt"],
    director: "Damien Chazelle",
    production: "Summit Entertainment",
    trailer_url: "https://www.youtube.com/embed/0pdqf4P9MB8"
  },
  // 27. THE NOTEBOOK (Romance, Drama)
  {
    id: 27,
    title: "The Notebook",
    type: "movie",
    overview: "An epic love story centered around an older man who reads aloud to a woman with Alzheimer's from a notebook detailing the romance of a young couple from different sides of the tracks.",
    poster_path: "/rNzQyW4f8B8cQeg7Dgj3n6eT5k9.jpg",
    backdrop_path: "/sua754O3z6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 7.9,
    release_date: "2004-06-25",
    runtime: 123,
    genres: ["Romance", "Drama"],
    cast: ["Ryan Gosling", "Rachel McAdams", "James Garner", "Gena Rowlands"],
    director: "Nick Cassavetes",
    production: "New Line Cinema",
    trailer_url: "https://www.youtube.com/embed/yDJIcYE32NU"
  },
  // 28. ABOUT TIME (Romance, Sci-Fi, Drama)
  {
    id: 28,
    title: "About Time",
    type: "movie",
    overview: "The night after another unsatisfactory New Year's party, Tim's father reveals that the men in his family have always had the ability to travel through time. Tim can't change history, but he can change what happens and has happened in his own life-so he decides to make his world a better place... by getting a girlfriend.",
    poster_path: "/2Gfjn962aaFSD6eST6QU3oLDZTo.jpg",
    backdrop_path: "/7d5a576208Cc5U1tM636uF2uL8O.jpg",
    vote_average: 7.9,
    release_date: "2013-09-04",
    runtime: 123,
    genres: ["Romance", "Sci-Fi", "Drama"],
    cast: ["Domhnall Gleeson", "Rachel McAdams", "Bill Nighy", "Tom Hollander"],
    director: "Richard Curtis",
    production: "Working Title Films",
    trailer_url: "https://www.youtube.com/embed/T7A810duHvw"
  },
  // 29. PRIDE & PREJUDICE (Romance, Drama)
  {
    id: 29,
    title: "Pride & Prejudice",
    type: "movie",
    overview: "Sparks fly when spirited Elizabeth Bennet meets single, rich, and proud Mr. Darcy. But Mr. Darcy reluctantly finds himself falling in love with a woman beneath his class. Can each overcome their own pride and prejudice?",
    poster_path: "/sGjIvtVvTlWnia2zfJfHz81pZ9Q.jpg",
    backdrop_path: "/ts54t8k9Xn9B2ZtG3yR7Kk314v9.jpg",
    vote_average: 8.1,
    release_date: "2005-09-16",
    runtime: 129,
    genres: ["Romance", "Drama"],
    cast: ["Keira Knightley", "Matthew Macfadyen", "Brenda Blethyn", "Donald Sutherland"],
    director: "Joe Wright",
    production: "Focus Features",
    trailer_url: "https://www.youtube.com/embed/1dYv5u6v55Y"
  },
  // 30. GLADIATOR (Action, Drama)
  {
    id: 30,
    title: "Gladiator",
    type: "movie",
    overview: "In the year 180, the death of Emperor Marcus Aurelius throws the Roman Empire into chaos. Maximus is one of the Roman army's most capable and trusted generals and a key advisor to the Emperor. As Marcus' devious son Commodus ascends to the throne, Maximus is set to be executed. He escapes, but is captured by slave traders and forced to become a gladiator.",
    poster_path: "/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    backdrop_path: "/nMKdUUueJZ57qtjTRLBUSBmge6c.jpg",
    vote_average: 8.2,
    release_date: "2000-05-01",
    runtime: 155,
    genres: ["Action", "Drama"],
    cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
    director: "Ridley Scott",
    production: "DreamWorks Pictures",
    trailer_url: "https://www.youtube.com/embed/ol67qo3WhZw"
  },
  // 31. MAD MAX: FURY ROAD (Action, Sci-Fi)
  {
    id: 31,
    title: "Mad Max: Fury Road",
    type: "movie",
    overview: "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and almost everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
    poster_path: "/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    backdrop_path: "/rAiw1ptqydR4u6sgzcj5q66Jt6c.jpg",
    vote_average: 7.6,
    release_date: "2015-05-13",
    runtime: 120,
    genres: ["Action", "Sci-Fi"],
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult", "Hugh Keays-Byrne"],
    director: "George Miller",
    production: "Warner Bros. Pictures",
    trailer_url: "https://www.youtube.com/embed/hEJnMQG9124"
  },
  // 32. JOHN WICK (Action, Thriller)
  {
    id: 32,
    title: "John Wick",
    type: "movie",
    overview: "John Wick is a legendary hitman who retired from his violent career after marrying the love of his life. Her sudden death leaves John in deep mourning. When sadistic mobster Iosef Tarasov and his thugs steal John's prized 1969 Mustang and kill the puppy that was a last gift from his wife, John unleashes the ruthless killing machine within.",
    poster_path: "/fZPSd91yGE9fCcCe6OoQr6E3Bev.jpg",
    backdrop_path: "/7d5a576208Cc5U1tM636uF2uL8O.jpg",
    vote_average: 7.4,
    release_date: "2014-10-22",
    runtime: 101,
    genres: ["Action", "Thriller"],
    cast: ["Keanu Reeves", "Michael Nyqvist", "Alfie Allen", "Adrianne Palicki"],
    director: "Chad Stahelski",
    production: "Summit Entertainment",
    trailer_url: "https://www.youtube.com/embed/2AUmvWm5R14"
  },
  // 33. TOP GUN: MAVERICK (Action, Drama)
  {
    id: 33,
    title: "Top Gun: Maverick",
    type: "movie",
    overview: "After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.",
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop_path: "/5Pv262zSj6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.2,
    release_date: "2022-05-24",
    runtime: 130,
    genres: ["Action", "Drama"],
    cast: ["Tom Cruise", "Miles Teller", "Jennifer Connelly", "Jon Hamm"],
    director: "Joseph Kosinski",
    production: "Skydance Media",
    trailer_url: "https://www.youtube.com/embed/giXcoYmT0Gs"
  },
  // 34. FORD V FERRARI (Action, Drama)
  {
    id: 34,
    title: "Ford v Ferrari",
    type: "movie",
    overview: "American car designer Carroll Shelby and the British-born driver Ken Miles work together to battle corporate interference, the laws of physics, and their own personal demons to build a revolutionary race car for Ford Motor Company and take on the dominating race cars of Enzo Ferrari at the 24 Hours of Le Mans in France in 1966.",
    poster_path: "/dR1Ju50iudrOh3YgfwkAU1g2HZe.jpg",
    backdrop_path: "/nMKdUUueJZ57qtjTRLBUSBmge6c.jpg",
    vote_average: 8.0,
    release_date: "2019-11-13",
    runtime: 152,
    genres: ["Action", "Drama"],
    cast: ["Matt Damon", "Christian Bale", "Jon Bernthal", "Caitríona Balfe"],
    director: "James Mangold",
    production: "20th Century Fox",
    trailer_url: "https://www.youtube.com/embed/zyYgDtY2AMY"
  },
  // 35. BREAKING BAD (Drama, Thriller) - TV SHOW
  {
    id: 35,
    title: "Breaking Bad",
    type: "tv",
    overview: "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdrop_path: "/ts54t8k9Xn9B2ZtG3yR7Kk314v9.jpg",
    vote_average: 9.5,
    release_date: "2008-01-20",
    runtime: 49, // average episode runtime
    genres: ["Drama", "Thriller"],
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Bob Odenkirk"],
    director: "Vince Gilligan (Creator)",
    production: "Sony Pictures Television",
    trailer_url: "https://www.youtube.com/embed/HhesaQXLuRY"
  },
  // 36. STRANGER THINGS (Sci-Fi, Thriller, Horror) - TV SHOW
  {
    id: 36,
    title: "Stranger Things",
    type: "tv",
    overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop_path: "/56v2a6t0YwHbc1g36UggOAcHd65.jpg",
    vote_average: 8.6,
    release_date: "2016-07-15",
    runtime: 50,
    genres: ["Sci-Fi", "Thriller", "Horror"],
    cast: ["Winona Ryder", "David Harbour", "Millie Bobby Brown", "Finn Wolfhard"],
    director: "The Duffer Brothers (Creators)",
    production: "Netflix",
    trailer_url: "https://www.youtube.com/embed/b9EkMc79ZSU"
  },
  // 37. GAME OF THRONES (Action, Drama) - TV SHOW
  {
    id: 37,
    title: "Game of Thrones",
    type: "tv",
    overview: "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.",
    poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
    backdrop_path: "/sua754O3z6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.4,
    release_date: "2011-04-17",
    runtime: 60,
    genres: ["Action", "Drama"],
    cast: ["Emilia Clarke", "Kit Harington", "Lena Headey", "Peter Dinklage"],
    director: "David Benioff, D.B. Weiss (Creators)",
    production: "HBO",
    trailer_url: "https://www.youtube.com/embed/bjqEWgDVy04"
  },
  // 38. THE LAST OF US (Action, Drama, Thriller) - TV SHOW
  {
    id: 38,
    title: "The Last of Us",
    type: "tv",
    overview: "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey.",
    poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
    backdrop_path: "/7Ry7z6j2E7OAJB1gj9xt7a92w1.jpg",
    vote_average: 8.7,
    release_date: "2023-01-15",
    runtime: 55,
    genres: ["Action", "Drama", "Thriller"],
    cast: ["Pedro Pascal", "Bella Ramsey", "Gabriel Luna", "Anna Torv"],
    director: "Craig Mazin, Neil Druckmann (Creators)",
    production: "HBO",
    trailer_url: "https://www.youtube.com/embed/uLtkt8BonwM"
  },
  // 39. WEDNESDAY (Comedy, Horror, Thriller) - TV SHOW
  {
    id: 39,
    title: "Wednesday",
    type: "tv",
    overview: "A sleuthing, supernaturally infused mystery charting Wednesday Addams' years as a student at Nevermore Academy. She attempts to master her emerging psychic ability, thwart a monstrous killing spree that has terrorized the local town, and solve the supernatural mystery that embroiled her parents 25 years ago.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    backdrop_path: "/iH7H5R4zrc62Erz4ur9g36g754O.jpg",
    vote_average: 8.0,
    release_date: "2022-11-23",
    runtime: 45,
    genres: ["Comedy", "Horror", "Thriller"],
    cast: ["Jenna Ortega", "Gwendoline Christie", "Riki Lindhome", "Christina Ricci"],
    director: "Tim Burton",
    production: "MGM Television",
    trailer_url: "https://www.youtube.com/embed/Di310WS8zLk"
  },
  // 40. THE OFFICE (Comedy) - TV SHOW
  {
    id: 40,
    title: "The Office",
    type: "tv",
    overview: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium. In Scranton, Pennsylvania, a branch of the Dunder Mifflin Paper Co. is managed by regional manager Michael Scott.",
    poster_path: "/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg",
    backdrop_path: "/ts54t8k9Xn9B2ZtG3yR7Kk314v9.jpg",
    vote_average: 8.6,
    release_date: "2005-03-24",
    runtime: 22,
    genres: ["Comedy"],
    cast: ["Steve Carell", "Rainn Wilson", "John Krasinski", "Jenna Fischer"],
    director: "Greg Daniels (Developer)",
    production: "Deedle-Dee Productions",
    trailer_url: "https://www.youtube.com/embed/LHOtME2DLyI"
  },
  // 41. FRIENDS (Comedy, Romance) - TV SHOW
  {
    id: 41,
    title: "Friends",
    type: "tv",
    overview: "Follow the lives of six reckless adults living in Manhattan, as they indulge in adventures which make their lives both troublesome and happening.",
    poster_path: "/f496cm9enuEsZkSPzCwnTESEK5s.jpg",
    backdrop_path: "/56v2a6t0YwHbc1g36UggOAcHd65.jpg",
    vote_average: 8.5,
    release_date: "1994-09-22",
    runtime: 22,
    genres: ["Comedy", "Romance"],
    cast: ["Jennifer Aniston", "Courteney Cox", "Lisa Kudrow", "Matt LeBlanc", "Matthew Perry", "David Schwimmer"],
    director: "David Crane, Marta Kauffman (Creators)",
    production: "Warner Bros. Television",
    trailer_url: "https://www.youtube.com/embed/hDNNmeeJs1Q"
  },
  // 42. TED LASSO (Comedy, Drama) - TV SHOW
  {
    id: 42,
    title: "Ted Lasso",
    type: "tv",
    overview: "American college football coach Ted Lasso is hired to manage a British soccer team, AFC Richmond, despite having no experience. But what he lacks in knowledge, he makes up for with optimism, underdog determination... and biscuits.",
    poster_path: "/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg",
    backdrop_path: "/7d5a576208Cc5U1tM636uF2uL8O.jpg",
    vote_average: 8.4,
    release_date: "2020-08-14",
    runtime: 40,
    genres: ["Comedy", "Drama"],
    cast: ["Jason Sudeikis", "Hannah Waddingham", "Jeremy Swift", "Phil Dunster"],
    director: "Bill Lawrence, Jason Sudeikis (Creators)",
    production: "Warner Bros. Television",
    trailer_url: "https://www.youtube.com/embed/3u7EIiohs6U"
  },
  // 43. BLACK MIRROR (Sci-Fi, Thriller) - TV SHOW
  {
    id: 43,
    title: "Black Mirror",
    type: "tv",
    overview: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
    poster_path: "/7PRddO7z7mcPi21nZTCMGShAyy1.jpg",
    backdrop_path: "/5Pv262zSj6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.3,
    release_date: "2011-12-04",
    runtime: 60,
    genres: ["Sci-Fi", "Thriller"],
    cast: ["Jesse Plemons", "Cristin Milioti", "Jimmi Simpson", "Michaela Coel"],
    director: "Charlie Brooker (Creator)",
    production: "House of Tomorrow",
    trailer_url: "https://www.youtube.com/embed/V0XOApF5nLU"
  },
  // 44. SEVERANCE (Sci-Fi, Thriller, Drama) - TV SHOW
  {
    id: 44,
    title: "Severance",
    type: "tv",
    overview: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
    poster_path: "/lFf6LLrQjYldcZItzOkGmMMigP7.jpg",
    backdrop_path: "/8Zg0n57521j4Ggu3fN622aZ362w.jpg",
    vote_average: 8.4,
    release_date: "2022-02-17",
    runtime: 50,
    genres: ["Sci-Fi", "Thriller", "Drama"],
    cast: ["Adam Scott", "Zach Cherry", "Britt Lower", "Patricia Arquette"],
    director: "Dan Erickson (Creator), Ben Stiller",
    production: "Red Hour Productions",
    trailer_url: "https://www.youtube.com/embed/xKTgpdpJ1dU"
  },
  // 45. SUCCESSION (Drama) - TV SHOW
  {
    id: 45,
    title: "Succession",
    type: "tv",
    overview: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.",
    poster_path: "/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg",
    backdrop_path: "/hiKazoRsw2m9qg6511g2w15asOB.jpg",
    vote_average: 8.3,
    release_date: "2018-06-03",
    runtime: 60,
    genres: ["Drama"],
    cast: ["Brian Cox", "Jeremy Strong", "Sarah Snook", "Kieran Culkin"],
    director: "Jesse Armstrong (Creator)",
    production: "Gary Sanchez Productions",
    trailer_url: "https://www.youtube.com/embed/OzYxJV_JH3U"
  },
  // 46. THE BEAR (Drama, Comedy) - TV SHOW
  {
    id: 46,
    title: "The Bear",
    type: "tv",
    overview: "A young chef from the fine dining world returns to Chicago to run his family sandwich shop after a heartbreaking death.",
    poster_path: "/sHFlbKS3WLqMnp9t2ghADIJFnuQ.jpg",
    backdrop_path: "/7Ry7z6j2E7OAJB1gj9xt7a92w1.jpg",
    vote_average: 8.5,
    release_date: "2022-06-23",
    runtime: 30,
    genres: ["Drama", "Comedy"],
    cast: ["Jeremy Allen White", "Ebon Moss-Bachrach", "Ayo Edebiri", "Lionel Boyce"],
    director: "Christopher Storer (Creator)",
    production: "FX Productions",
    trailer_url: "https://www.youtube.com/embed/i5U-w1yRy4c"
  },
  // 47. BEEF (Drama, Comedy, Thriller) - TV SHOW
  {
    id: 47,
    title: "Beef",
    type: "tv",
    overview: "Two people let a road rage incident burrow into their minds and slowly consume their every thought and action.",
    poster_path: "/1V4SP1cQO2mV4u3Xw9s1Y0N7P4.jpg",
    backdrop_path: "/sua754O3z6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.1,
    release_date: "2023-04-06",
    runtime: 35,
    genres: ["Drama", "Comedy", "Thriller"],
    cast: ["Steven Yeun", "Ali Wong", "Joseph Lee", "Young Mazino"],
    director: "Lee Sung Jin (Creator)",
    production: "A24",
    trailer_url: "https://www.youtube.com/embed/YKNkG_K4WcA"
  },
  // 48. EUPHORIA (Drama) - TV SHOW
  {
    id: 48,
    title: "Euphoria",
    type: "tv",
    overview: "A look at the life of a group of high school students as they navigate love and friendships in a world of drugs, sex, trauma, and social media.",
    poster_path: "/jtnfNzqZwN4E32FGGxx1YZaBWWf.jpg",
    backdrop_path: "/nMKdUUueJZ57qtjTRLBUSBmge6c.jpg",
    vote_average: 8.3,
    release_date: "2019-06-16",
    runtime: 55,
    genres: ["Drama"],
    cast: ["Zendaya", "Hunter Schafer", "Sydney Sweeney", "Jacob Elordi"],
    director: "Sam Levinson (Creator)",
    production: "A24",
    trailer_url: "https://www.youtube.com/embed/URysY0gBDpU"
  },
  // 49. DARK (Sci-Fi, Thriller, Drama) - TV SHOW
  {
    id: 49,
    title: "Dark",
    type: "tv",
    overview: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery that spans three generations.",
    poster_path: "/5LoHuHWA4H8jElFlZDvsmU2n63b.jpg",
    backdrop_path: "/rAiw1ptqydR4u6sgzcj5q66Jt6c.jpg",
    vote_average: 8.4,
    release_date: "2017-12-01",
    runtime: 60,
    genres: ["Sci-Fi", "Thriller", "Drama"],
    cast: ["Louis Hofmann", "Oliver Masucci", "Jördis Triebel", "Maja Schöne"],
    director: "Baran bo Odar, Jantje Friese (Creators)",
    production: "Netflix",
    trailer_url: "https://www.youtube.com/embed/rrwycJ08PSA"
  },
  // 50. FLEABAG (Comedy, Drama, Romance) - TV SHOW
  {
    id: 50,
    title: "Fleabag",
    type: "tv",
    overview: "A dry-witted woman, known only as Fleabag, navigates life and love in London while trying to cope with tragedy.",
    poster_path: "https://media-cache.cinematerial.com/p/500x/jc78ert9/fleabag-movie-poster.jpg?v=1570580878",
    backdrop_path: "/7d5a576208Cc5U1tM636uF2uL8O.jpg",
    vote_average: 8.5,
    release_date: "2016-07-21",
    runtime: 25,
    genres: ["Comedy", "Drama", "Romance"],
    cast: ["Phoebe Waller-Bridge", "Sian Clifford", "Andrew Scott", "Olivia Colman"],
    director: "Phoebe Waller-Bridge (Creator)",
    production: "Two Brothers Pictures",
    trailer_url: "https://www.youtube.com/embed/I5U-w1yRy4c"
  },
  // 51. BRIDGERTON (Romance, Drama) - TV SHOW
  {
    id: 51,
    title: "Bridgerton",
    type: "tv",
    overview: "Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.",
    poster_path: "/luoKpgVwi1E5nQsi7W0UuKHu2Rq.jpg",
    backdrop_path: "/5Pv262zSj6j2E7OAJB1gj9xt7a.jpg",
    vote_average: 8.1,
    release_date: "2020-12-25",
    runtime: 60,
    genres: ["Romance", "Drama"],
    cast: ["Adjoa Andoh", "Julie Andrews", "Jonathan Bailey", "Nicola Coughlan"],
    director: "Chris Van Dusen (Creator)",
    production: "Shondaland",
    trailer_url: "https://www.youtube.com/embed/gpv7ayf_tyE"
  },
  // 52. SQUID GAME (Thriller, Action, Drama) - TV SHOW
  {
    id: 52,
    title: "Squid Game",
    type: "tv",
    overview: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    backdrop_path: "/7Ry7z6j2E7OAJB1gj9xt7a92w1.jpg",
    vote_average: 8.3,
    release_date: "2021-09-17",
    runtime: 55,
    genres: ["Thriller", "Action", "Drama"],
    cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-jun", "Jung Ho-yeon"],
    director: "Hwang Dong-hyuk (Creator)",
    production: "Siren Pictures",
    trailer_url: "https://www.youtube.com/embed/oqxAJKy0R4A"
  }
];
